version: '3'

services:
  java:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    container_name: backend_2
    restart: no
    ports:
      - '8080:8080'
    volumes:
      - './:/app'